### ISSUE TITLE
Dependency Error:  Cannot find module './setPrototypeOf' from '../node_modules/jimp/browser/lib'

### ISSUE THREAD

**Issue by Chris-DuCharme** [researchgate/emailonacid#59]
I am attempting to setup a test though Cypress.  

However, i'm finding I can not import @researchgate/emailonacid-snapshot

When adding the following to a test,
`const { createEmail } = require('@researchgate/emailonacid-snapshot');`
or
`import { createEmail } from '@researchgate/emailonacid-snapshot';`

I get the following dependency error:

Error: Cannot find module './setPrototypeOf' from '../node_modules/jimp/browser/lib'

I have been spending the last few hours trying to figure out how to get around it with no luck.

jimp is present.  I have even tried manually dropping jimp into place verses having npm install it and am getting the same results.

**Comment by danez** [comment]
Thanks for reporting, I will have a look in some days.

**Comment by justinvdm** [comment]
Just took a quick look now, it would seem as if jimp isn't compatible with cypress/electron. Running a test suite file with cypress that simply does an `import 'jimp'` in (latest jimp, 0.12.1)  gives a similar error:

```
Error: Cannot find module '../helpers/typeof' from '.../node_modules/jimp/browser/lib'
```

I don't know cypress and electron very well, but it looks like they're using the `browser` field in jimp's package.json as the entry point module, which points to `browser/lib/jimp.js`. I'm guessing the scoped `require`s defined in that bundle are not being used, and the globally defined `require` in electron's environment is being used instead. Probably best to file a bug with [jimp](https://github.com/oliver-moran/jimp) to get it working with cypress/electron.

That all said, we haven't used emailonacid-snapshot with cypress before, so there could also be other hurdles in the way after the jimp incompatibility is fixed.

**Comment by Chris-DuCharme** [comment]
Thanks, 

I'll try my luck with filing a bug with jimp.

The error you got I actually got too on the first run.  Then each subsequent run I got the error that I posted.  

I'll report back if / when this gets resolved and let you know if there are any other compatibility issues.

**Comment by justinvdm** [comment]
Thank you @Chris-DuCharme 👍  I'll close this for now then.
